"""rename production_date on cheeses

Revision ID: 61884f3e14ef
Revises: 34b976f627b0
Create Date: 2024-09-23 13:59:30.462650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61884f3e14ef'
down_revision = '34b976f627b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cheeses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('production_date', sa.DateTime(), nullable=True))
        batch_op.drop_column('productions')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cheeses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('productions', sa.DATETIME(), nullable=True))
        batch_op.drop_column('production_date')

    # ### end Alembic commands ###
